const STAGES=[
  {id:'contact',label:'Đang trao đổi',tone:'#2563eb',soft:'#eaf1ff'},
  {id:'signed',label:'Đã ký hợp đồng',tone:'#e99718',soft:'#fff4df'},
  {id:'testing',label:'Đang test',tone:'#7c3aed',soft:'#f1eaff'},
  {id:'live',label:'Go live',tone:'#00a85e',soft:'#dff7eb'},
  {id:'noresponse',label:'Không phản hồi',tone:'#64748b',soft:'#eef1f5'}
];
const seed=[
 {id:101,company:'CÔNG TY CỔ PHẦN HUNDRED DOT',contact:'Hải Phan',phone:'0913755169',email:'haiphan.works@gmail.com',taxId:'0318338337',source:'Website',status:'noresponse',qualification:'unrated',owner:'Thuý Hằng',created:'2026-07-24',followup:'2026-08-05',apiInterest:'Balance Hook, Virtual Account, QR Pay, Pay Out, Transactions, E-Invoice',product:'Internal accounting system + ecommerce',note:'Đăng ký nhận credit API – CAS for Startup.'},
 {id:102,company:'CÔNG TY CỔ PHẦN ECONATIONS',contact:'Đầu mối Ecofly',phone:'0839776779',email:'system.econations@gmail.com',taxId:'4201994038',website:'https://econations.vn',source:'Website',status:'contact',qualification:'unrated',owner:'Thuý Hằng',created:'2026-07-25',followup:'2026-08-05',apiInterest:'QR Pay, Transactions',product:'Ecofly – nền tảng SaaS “nhận nuôi trồng” cho nông trại · ecofly.vn · econations.vn',note:'Cần xác nhận thanh toán tự động, đọc lịch sử giao dịch và đối soát đơn hàng. Quan tâm Cas Link và Transactions API.'},
 {id:104,company:'CÔNG TY CỔ PHẦN CLI NUTRIX',contact:'Đầu mối CLI NUTRIX',phone:'0984988359',email:'hoc.gk2@gmail.com',taxId:'0319436143',source:'Website',status:'signed',qualification:'unrated',owner:'Thuý Hằng',created:'2026-07-29',followup:'2026-08-07',apiInterest:'Balance Hook, Virtual Account, QR Pay, Pay Out, Transactions, eKYC, E-Invoice',product:'Mimi Wallet – nền tảng tài chính số dành cho doanh nghiệp nhỏ và siêu nhỏ (SME)',note:'Ứng dụng AI chấm điểm tín dụng từ dữ liệu giao dịch, kết hợp eKYC và bảo mật hậu lượng tử.'},
 {id:105,company:'CÔNG TY CỔ PHẦN NUTREE AI VIỆT NAM',contact:'Alex Nguyễn',phone:'0948580529',email:'alex.nguyen@nutreeai.com',taxId:'2200826051',source:'Website',status:'contact',qualification:'unrated',owner:'Thuý Hằng',created:'2026-07-30',followup:'2026-08-08',apiInterest:'Không chọn',product:'Nutree – ứng dụng AI dinh dưỡng và quản lý sức khoẻ cho người dùng Việt Nam',note:'Theo dõi dinh dưỡng, xây dựng kế hoạch ăn uống cá nhân hóa, cân nặng và mục tiêu sức khỏe.'}
];
let customers=JSON.parse(localStorage.getItem('cas-crm-customers')||'null')||seed;
if(localStorage.getItem('cas-crm-clean-real-data')!=='real-leads-only-v3'){
 customers=structuredClone(seed);
 localStorage.setItem('cas-crm-customers',JSON.stringify(customers));
 localStorage.setItem('cas-crm-clean-real-data','real-leads-only-v3');
}
if(localStorage.getItem('cas-crm-stage-version')!=='five-custom-stages-v1'){
 customers=customers.map(x=>({...x,status:x.status==='new'?'contact':x.status}));
 localStorage.setItem('cas-crm-customers',JSON.stringify(customers));
 localStorage.setItem('cas-crm-stage-version','five-custom-stages-v1');
}
if(localStorage.getItem('cas-crm-owner-version')!=='thuy-hang-v1'){
 customers=customers.map(x=>({...x,owner:x.owner==='Thu Hằng'?'Thuý Hằng':x.owner}));
 localStorage.setItem('cas-crm-customers',JSON.stringify(customers));
 localStorage.setItem('cas-crm-owner-version','thuy-hang-v1');
}
if(!customers.length&&localStorage.getItem('cas-crm-empty-recovery')!=='four-real-leads-v1'){
 customers=structuredClone(seed).filter(x=>x.id!==103).map(x=>({...x,status:x.id===104?'signed':x.id===101?'noresponse':'contact'}));
 localStorage.setItem('cas-crm-customers',JSON.stringify(customers));
 localStorage.setItem('cas-crm-empty-recovery','four-real-leads-v1');
}
if(localStorage.getItem('cas-crm-website-version')!=='company-links-v1'){
 customers=customers.map(x=>x.id===102&&!x.website?{...x,website:'https://econations.vn'}:x);
 localStorage.setItem('cas-crm-customers',JSON.stringify(customers));
 localStorage.setItem('cas-crm-website-version','company-links-v1');
}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const SHEETS_URL=String(window.CAS_SHEETS_URL||'').trim();
let statusHistory=[];
let monthlyReports=JSON.parse(localStorage.getItem('cas-crm-monthly-reports')||'null')||{'2026-07':'Tháng 7, sau khi triển khai bài đăng trên Facebook, có 4 khách hàng điền form quan tâm đến chương trình CAS for Startup. Trong số đó, 1 khách hàng đã ký hợp đồng là CÔNG TY CỔ PHẦN CLI NUTRIX. Doanh nghiệp phát triển Mimi Wallet – nền tảng tài chính số dành cho doanh nghiệp nhỏ và siêu nhỏ (SME), kết hợp ứng dụng AI chấm điểm tín dụng từ dữ liệu giao dịch.'};
const setSyncStatus=message=>{const el=$('#syncStatus');if(el)el.textContent=message};
const save=()=>{localStorage.setItem('cas-crm-customers',JSON.stringify(customers));localStorage.setItem('cas-crm-monthly-reports',JSON.stringify(monthlyReports));syncToSheets()};
const restoreIdentifier=v=>{const s=String(v||'').trim();return /^\d{9}$/.test(s)?'0'+s:s};
const normalizeSheetDate=v=>{const s=String(v||'');if(!s)return '';if(!s.includes('T'))return s.slice(0,10);const d=new Date(s);if(Number.isNaN(d.getTime()))return s.slice(0,10);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)};
const normalizeCustomer=x=>({...x,id:Number(x?.id)||Date.now(),company:String(x?.company||''),contact:String(x?.contact||''),phone:restoreIdentifier(x?.phone),email:String(x?.email||''),taxId:restoreIdentifier(x?.taxId),website:String(x?.website||(Number(x?.id)===102?'https://econations.vn':'')),source:String(x?.source||'Website'),created:normalizeSheetDate(x?.created),status:STAGES.some(s=>s.id===x?.status)?x.status:'contact',qualification:['potential','not-potential'].includes(x?.qualification)?x.qualification:'unrated',owner:String(x?.owner||'Thuý Hằng'),followup:normalizeSheetDate(x?.followup),apiInterest:String(x?.apiInterest||''),product:String(x?.product||''),contractLink:String(x?.contractLink||''),appendixLink:String(x?.appendixLink||''),note:String(x?.note||'')});
async function syncToSheets(){if(!SHEETS_URL){setSyncStatus('Dữ liệu đang lưu trên thiết bị này');return}setSyncStatus('Đang đồng bộ Google Sheets...');try{const response=await fetch(SHEETS_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'sync',customers,reports:monthlyReports})});const result=await response.json();if(!result.ok)throw new Error(result.error||'Sync failed');statusHistory=result.history||statusHistory;setSyncStatus(`Đã đồng bộ Google Sheets · ${customers.length} khách hàng`)}catch(error){console.error(error);setSyncStatus('Không thể đồng bộ Google Sheets · dữ liệu vẫn được lưu trên thiết bị')}}
async function loadFromSheets(){if(!SHEETS_URL){setSyncStatus('Dữ liệu đang lưu trên thiết bị này');return}setSyncStatus('Đang tải dữ liệu từ Google Sheets...');try{const response=await fetch(`${SHEETS_URL}?t=${Date.now()}`);const result=await response.json();if(!result.ok)throw new Error(result.error||'Load failed');statusHistory=Array.isArray(result.history)?result.history:[];if(result.reports&&typeof result.reports==='object'&&Object.keys(result.reports).length){monthlyReports={...monthlyReports,...result.reports};localStorage.setItem('cas-crm-monthly-reports',JSON.stringify(monthlyReports))}const remoteCustomers=Array.isArray(result.customers)?result.customers:[];if(remoteCustomers.length){customers=remoteCustomers.map(normalizeCustomer).filter(x=>x.company);localStorage.setItem('cas-crm-customers',JSON.stringify(customers));refreshMonthFilter();renderAll();await syncToSheets();setSyncStatus(`Đã kết nối Google Sheets · ${customers.length} khách hàng`)}else if(customers.length){await syncToSheets()}else{renderMonthlyReport();setSyncStatus('Google Sheets chưa có khách hàng · hãy thêm khách hàng mới')}}catch(error){console.error(error);setSyncStatus('Không thể tải Google Sheets · đang dùng dữ liệu trên thiết bị')}}
let collapsedStages=new Set(JSON.parse(localStorage.getItem('cas-crm-collapsed-stages')||'[]'));
const esc=s=>String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const safeUrl=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
const initials=s=>s.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();
const fmt=d=>{if(!d)return '—';const date=new Date(String(d).slice(0,10)+'T12:00:00');return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(date)};
const stage=id=>STAGES.find(s=>s.id===id)||STAGES[0];
const filtered=()=>{let arr=[...customers];const month=$('#monthFilter')?.value;if(month&&month!=='all')arr=arr.filter(x=>x.created.startsWith(month));const q=$('#searchInput').value.toLowerCase();if(q)arr=arr.filter(x=>Object.values(x).some(v=>String(v).toLowerCase().includes(q)));return arr};
function refreshMonthFilter(preferred){const select=$('#monthFilter'),current=preferred||select.value||localStorage.getItem('cas-crm-report-month');const months=[...new Set(customers.map(x=>x.created?.slice(0,7)).filter(Boolean))].sort().reverse();select.innerHTML=`<option value="all">Tất cả thời gian</option>${months.map(m=>{const [y,mo]=m.split('-');return `<option value="${m}">Tháng ${mo} / ${y}</option>`}).join('')}`;select.value=current==='all'||months.includes(current)?current:(months[0]||'all');localStorage.setItem('cas-crm-report-month',select.value)}
function renderOverview(){const data=filtered(),selectedMonth=$('#monthFilter').value;$('#totalLeads').textContent=data.length;$('#donutTotal').textContent=data.length;
 const metrics=STAGES.map(s=>({s,count:data.filter(x=>x.status===s.id).length}));$('#metricGrid').innerHTML=metrics.map(({s,count})=>`<article class="metric" style="--tone:${s.tone}"><b>${count}</b><p>${s.label}</p><small>${Math.round(count/(data.length||1)*100)}%</small></article>`).join('');
 const max=Math.max(...STAGES.map(s=>data.filter(x=>x.status===s.id).length),1);$('#funnel').innerHTML=STAGES.map(s=>{const n=data.filter(x=>x.status===s.id).length;return `<div class="funnel-row"><span>${s.label}</span><div class="funnel-bar"><i style="--w:${n/max*100}%;--tone:${s.tone}"></i></div><b>${n}</b></div>`}).join('');
 const src=['Website','Facebook Ads','Giới thiệu'], colors=['#00a85e','#0a0a0a','#aeb9b3'];const counts=src.map(x=>data.filter(c=>c.source===x).length);let cursor=0;const stops=counts.map((n,i)=>{const a=cursor;cursor+=n/(data.length||1)*100;return `${colors[i]} ${a}% ${cursor}%`});$('#sourceDonut').style.background=`conic-gradient(${stops.join(',')})`;$('#sourceLegend').innerHTML=src.map((x,i)=>`<div class="legend-row" style="--tone:${colors[i]}"><i></i><span>${x}</span><b>${counts[i]}</b></div>`).join('');
 $('#followupList').innerHTML=[...data].sort((a,b)=>String(a.followup||'9999').localeCompare(String(b.followup||'9999'))).slice(0,3).map((x,i)=>{const s=stage(x.status);return `<div class="follow-card"><div class="company-logo" style="--tone:${s.tone};--soft:${s.soft}">${initials(x.company)}</div><div><b>${esc(x.company)}</b><small>${esc(x.contact)} · ${s.label}</small></div><span class="due">${fmt(x.followup).slice(0,5)}</span></div>`}).join('');
 const signed=data.filter(x=>['signed','testing','live'].includes(x.status)).length,live=data.filter(x=>x.status==='live').length,noresponse=data.filter(x=>x.status==='noresponse').length;let previous=[];if(/^\d{4}-\d{2}$/.test(selectedMonth)){const d=new Date(selectedMonth+'-01T12:00:00');d.setMonth(d.getMonth()-1);const pm=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;previous=customers.filter(x=>x.created?.startsWith(pm))}const delta=data.length-previous.length;$('#totalTrend').textContent=selectedMonth==='all'?'Tất cả dữ liệu':`${delta>=0?'+':''}${delta} khách so với tháng trước`;$('#conversionGrid').innerHTML=[['Tỷ lệ ký hợp đồng',signed,'signed'],['Tỷ lệ Go live',live,'live'],['Không phản hồi',noresponse,'noresponse']].map(([label,count,id])=>{const s=stage(id),rate=Math.round(count/(data.length||1)*100);return `<article class="conversion-card" style="--tone:${s.tone};--soft:${s.soft}"><div><span>${label}</span><b>${rate}%</b></div><small>${count}/${data.length} khách hàng</small><i><em style="width:${rate}%"></em></i></article>`}).join('');renderMonthlyReport();
}
function renderMonthlyReport(){const month=$('#monthFilter').value,key=/^\d{4}-\d{2}$/.test(month)?month:'';$('#briefMonth').textContent=key?key.slice(5):'—';$('#monthlyReport').value=key?(monthlyReports[key]||''):'';$('#monthlyReport').disabled=!key;$('#saveMonthlyReport').disabled=!key;$('#generateMonthlyReport').disabled=!key;$('#briefState').textContent=key?'Đã lưu':'Chọn một tháng';$('#briefState').classList.remove('editing')}
function generateMonthlyReport(){const month=$('#monthFilter').value;if(!/^\d{4}-\d{2}$/.test(month))return;const box=$('#monthlyReport');if(box.value.trim()&&!confirm('Thay nội dung hiện tại bằng bản nhận định được hệ thống soạn lại?'))return;const data=customers.filter(x=>x.created?.startsWith(month)),monthNumber=Number(month.slice(5)),year=month.slice(0,4);if(!data.length){box.value=`Trong tháng ${monthNumber}/${year}, chưa ghi nhận khách hàng mới cho chương trình CAS for Startup. Cần tiếp tục theo dõi các kênh tiếp cận và cập nhật dữ liệu khi có khách hàng phát sinh.`}else{const counts=Object.fromEntries(STAGES.map(s=>[s.id,data.filter(x=>x.status===s.id).length])),sources=[...new Set(data.map(x=>x.source).filter(Boolean))].map(source=>({source,count:data.filter(x=>x.source===source).length})).sort((a,b)=>b.count-a.count),sourceText=sources.map(x=>`${x.count} khách từ ${x.source}`).join(', '),progressed=data.filter(x=>['signed','testing','live'].includes(x.status)),highlight=progressed[0]||data[0],product=String(highlight.product||highlight.note||'').trim(),statusParts=STAGES.map(s=>counts[s.id]?`${counts[s.id]} khách ${s.label.toLowerCase()}`:'').filter(Boolean),previousDate=new Date(`${month}-01T12:00:00`);previousDate.setMonth(previousDate.getMonth()-1);const previousKey=`${previousDate.getFullYear()}-${String(previousDate.getMonth()+1).padStart(2,'0')}`,previousCount=customers.filter(x=>x.created?.startsWith(previousKey)).length,comparison=previousCount?` So với tháng trước, số khách hàng ${data.length>previousCount?`tăng ${data.length-previousCount}`:data.length<previousCount?`giảm ${previousCount-data.length}`:'không thay đổi'} (${previousCount} khách trong tháng trước).`:'';let next='';if(counts.contact)next+=` Trong thời gian tới, cần tiếp tục trao đổi và làm rõ nhu cầu với ${counts.contact} khách đang quan tâm.`;if(counts.noresponse)next+=` Đồng thời, cần follow-up lại ${counts.noresponse} khách chưa phản hồi.`;box.value=`Trong tháng ${monthNumber}/${year}, chương trình CAS for Startup ghi nhận ${data.length} khách hàng mới (${sourceText}). Tình hình pipeline hiện tại gồm ${statusParts.join(', ')}.${comparison} Khách hàng nổi bật là ${highlight.company}, hiện ở giai đoạn ${stage(highlight.status).label.toLowerCase()}${product?` và đang phát triển ${product}`:''}.${next}`};box.focus();$('#briefState').textContent='Bản nháp · Chưa lưu';$('#briefState').classList.add('editing');toast('Đã soạn bản nhận định')}
function renderKanban(){const data=filtered(),collapsedCount=STAGES.filter(s=>collapsedStages.has(s.id)).length,expandedWidth=Math.min(360,300+collapsedCount*15);$('#pipelineCount').textContent=`${data.length} cơ hội`;$('#kanban').style.gridTemplateColumns=STAGES.map(s=>collapsedStages.has(s.id)?'92px':`${expandedWidth}px`).join(' ');$('#kanban').innerHTML=STAGES.map(s=>{const cards=data.filter(x=>x.status===s.id),collapsed=collapsedStages.has(s.id);return `<section class="kanban-col ${collapsed?'collapsed':''}" data-stage="${s.id}" style="--tone:${s.tone};--soft:${s.soft}"><div class="col-head"><div><b>${s.label}</b><small>${cards.length} STARTUP</small></div><div class="col-actions"><span>${cards.length}</span><button class="collapse-btn" data-collapse="${s.id}" aria-label="${collapsed?'Mở rộng':'Thu gọn'} cột ${s.label}" title="${collapsed?'Mở rộng':'Thu gọn'}">${collapsed?'›':'‹'}</button></div></div><div class="cards">${cards.map(x=>{const contract=safeUrl(x.contractLink),appendix=safeUrl(x.appendixLink);return `<article class="deal-card" draggable="true" data-id="${x.id}"><div class="deal-stage">${s.label}</div><div class="deal-logo">${initials(x.company)}</div><div class="deal-top"><h3>${esc(x.company)}</h3><span class="source-badge" style="--tone:${x.source==='Website'?'#008e50':x.source==='Facebook Ads'?'#0a0a0a':'#67736d'};--soft:${x.source==='Website'?'#e8f8f0':x.source==='Facebook Ads'?'#eeeeee':'#eef1ef'}">${esc(x.source)}</span></div><p>${esc(x.product||x.note)}</p>${contract||appendix?`<div class="deal-docs">${contract?`<a href="${esc(contract)}" target="_blank" rel="noopener">↗ Hợp đồng</a>`:''}${appendix?`<a href="${esc(appendix)}" target="_blank" rel="noopener">↗ Phụ lục</a>`:''}</div>`:''}<div class="deal-meta"><span>${esc(x.contact)}</span><span class="followup-date">Follow-up ${fmt(x.followup).slice(0,5)}</span></div></article>`}).join('')}</div></section>`}).join('');$$('[data-collapse]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.collapse;collapsedStages.has(id)?collapsedStages.delete(id):collapsedStages.add(id);localStorage.setItem('cas-crm-collapsed-stages',JSON.stringify([...collapsedStages]));renderKanban()});$$('.kanban-col.collapsed').forEach(col=>col.onclick=e=>{if(e.target.closest('.collapse-btn'))return;collapsedStages.delete(col.dataset.stage);localStorage.setItem('cas-crm-collapsed-stages',JSON.stringify([...collapsedStages]));renderKanban()});bindDrag()}
function renderTable(){const data=filtered();$('#tableCount').textContent=`${data.length} khách hàng`;$('#customerTable').innerHTML=data.map(x=>{const s=stage(x.status);return `<tr><td><b>${esc(x.company)}</b><small>${esc(x.product||x.note).slice(0,55)}</small></td><td>${esc(x.contact)}<small>${esc(x.email)} · ${esc(x.phone)}</small></td><td>${esc(x.source)}</td><td><span class="status-badge" style="--tone:${s.tone};--soft:${s.soft}">${s.label}</span></td><td>${fmt(x.created)}</td><td>${esc(x.owner)}</td><td><button class="more-btn" data-edit="${x.id}" aria-label="Sửa">···</button></td></tr>`}).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openDialog(customers.find(x=>x.id==b.dataset.edit)))}
function linkWebsiteBadges(){ $$('.deal-card').forEach(card=>{const customer=customers.find(x=>String(x.id)===String(card.dataset.id)),website=safeUrl(customer?.website),badge=card.querySelector('.source-badge');if(!website||!badge)return;badge.outerHTML=`<a class="source-badge website-link" href="${esc(website)}" target="_blank" rel="noopener" title="Mở website của ${esc(customer.company)}">Website ↗</a>`}) }
const qualificationInfo=value=>value==='potential'?{label:'Tiềm năng',className:'potential'}:value==='not-potential'?{label:'Không tiềm năng',className:'not-potential'}:{label:'Chưa đánh giá',className:'unrated'};
const qualificationTagHTML=value=>{const info=qualificationInfo(value);return info?`<span class="qualification-tag ${info.className}">${info.label}</span>`:''};
function decorateQualificationTags(){$$('.deal-card').forEach(card=>{const customer=customers.find(x=>String(x.id)===String(card.dataset.id)),stageTag=card.querySelector('.deal-stage');if(!customer||!stageTag||card.querySelector('.qualification-select'))return;const row=document.createElement('div'),select=document.createElement('select');row.className='deal-tag-row';select.className=`qualification-select ${customer.qualification||'unrated'}`;select.setAttribute('aria-label',`Đánh giá ${customer.company}`);select.innerHTML='<option value="unrated">Chưa đánh giá</option><option value="potential">Tiềm năng</option><option value="not-potential">Không tiềm năng</option>';select.value=customer.qualification||'unrated';select.draggable=false;select.onmousedown=e=>e.stopPropagation();select.onclick=e=>e.stopPropagation();select.onchange=e=>{e.stopPropagation();customer.qualification=select.value;save();renderAll();toast('Đã cập nhật đánh giá khách hàng')};stageTag.parentNode.insertBefore(row,stageTag);row.append(stageTag,select)})}
function renderAll(){renderKanban();linkWebsiteBadges();renderTable();renderOverview()}
function bindDrag(){$$('.deal-card').forEach(card=>{card.ondragstart=()=>{card.dataset.dragged='1';card.classList.add('dragging')};card.ondragend=()=>{card.classList.remove('dragging');setTimeout(()=>delete card.dataset.dragged,80)};card.onclick=e=>{if(card.dataset.dragged||e.target.closest('a,button,select'))return;openCustomerSummary(customers.find(x=>x.id==card.dataset.id))}});$$('.kanban-col').forEach(col=>{col.ondragover=e=>e.preventDefault();col.ondrop=e=>{e.preventDefault();const card=$('.dragging');if(!card)return;const x=customers.find(x=>x.id==card.dataset.id);x.status=col.dataset.stage;save();renderAll();toast('Đã chuyển sang '+stage(x.status).label)}})}
const bindDragBase=bindDrag;bindDrag=()=>{linkWebsiteBadges();decorateQualificationTags();bindDragBase()};
function renderCustomerHistory(x){$('#historySection').style.display=x?'block':'none';if(!x)return;const items=statusHistory.filter(h=>String(h.customerId)===String(x.id)).sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp)));$('#statusHistory').innerHTML=items.length?items.map(h=>{const from=h.fromStatus?stage(h.fromStatus).label:'Khởi tạo',to=stage(h.toStatus).label,date=new Date(h.timestamp),time=Number.isNaN(date.getTime())?h.timestamp:new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(date);return `<div class="history-item"><i style="--tone:${stage(h.toStatus).tone}"></i><div><b>${esc(from)} → ${esc(to)}</b><small>${esc(h.owner||'')} · ${esc(time)}</small></div></div>`}).join(''):'<div class="history-empty">Chưa có thay đổi trạng thái được ghi nhận.</div>'}
function openCustomerSummary(x){if(!x)return;const s=stage(x.status),website=safeUrl(x.website),contract=safeUrl(x.contractLink),appendix=safeUrl(x.appendixLink),value=v=>esc(v)||'—';$('#summaryCompany').textContent=x.company;$('#summaryBody').innerHTML=`<div class="summary-status" style="--tone:${s.tone};--soft:${s.soft}"><span>${s.label}</span><small>Follow-up ${fmt(x.followup)}</small></div><section class="summary-highlight"><label>Sản phẩm / mô hình</label><p>${value(x.product||x.note)}</p></section><div class="summary-grid"><div><label>Người liên hệ</label><b>${value(x.contact)}</b></div><div><label>Người phụ trách</label><b>${value(x.owner)}</b></div><div><label>Điện thoại</label><b>${value(x.phone)}</b></div><div><label>Email</label><b>${value(x.email)}</b></div><div><label>Nguồn khách hàng</label><b>${value(x.source)}</b></div><div><label>Ngày liên hệ</label><b>${fmt(x.created)}</b></div></div><section class="summary-note"><label>API quan tâm</label><p>${value(x.apiInterest)}</p></section>${x.note?`<section class="summary-note"><label>Ghi chú</label><p>${value(x.note)}</p></section>`:''}${website||contract||appendix?`<div class="summary-links">${website?`<a href="${esc(website)}" target="_blank" rel="noopener">Website ↗</a>`:''}${contract?`<a href="${esc(contract)}" target="_blank" rel="noopener">Hợp đồng ↗</a>`:''}${appendix?`<a href="${esc(appendix)}" target="_blank" rel="noopener">Phụ lục ↗</a>`:''}</div>`:''}`;$('#summaryToCustomers').dataset.id=x.id;$('#summaryDialog').showModal()}
const openCustomerSummaryBase=openCustomerSummary;openCustomerSummary=x=>{openCustomerSummaryBase(x);const status=$('#summaryBody .summary-status'),tag=qualificationTagHTML(x?.qualification);if(status&&tag){const label=status.querySelector('span');label.insertAdjacentHTML('afterend',tag);label.parentElement.classList.add('summary-status-main')}};
function openDialog(x){$('#customerForm').reset();$('#customerId').value=x?.id||'';$('#dialogTitle').textContent=x?'Cập nhật khách hàng':'Thêm startup mới';$('#deleteCustomerBtn').classList.toggle('visible',Boolean(x));['company','contact','phone','email','taxId','website','source','created','status','qualification','owner','followup','apiInterest','product','contractLink','appendixLink','note'].forEach(k=>$('#'+k).value=x?.[k]||($('#'+k).value||''));if(!x){const now=new Date(),localDate=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);$('#owner').value='Thuý Hằng';$('#created').value=localDate;$('#followup').value=localDate}renderCustomerHistory(x);$('#customerDialog').showModal()}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function switchView(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+name+'View').classList.add('active');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('#pageTitle').textContent={overview:'Tổng quan CAS for Startup',pipeline:'Pipeline khách hàng',customers:'Danh sách khách hàng',report:'Báo cáo tháng'}[name];$('#pageSubtitle').textContent={overview:'Báo cáo tình hình khách hàng theo kỳ đã chọn.',pipeline:'Theo dõi và cập nhật tiến độ từng khách hàng.',customers:'Tra cứu và quản lý toàn bộ hồ sơ khách hàng.',report:'Tổng hợp kết quả, điểm nổi bật và định hướng tiếp theo.'}[name]}
$('#monthlyReport').oninput=()=>{$('#briefState').textContent='Chưa lưu';$('#briefState').classList.add('editing')};
$('#generateMonthlyReport').onclick=generateMonthlyReport;
$('#saveMonthlyReport').onclick=()=>{const month=$('#monthFilter').value;if(!/^\d{4}-\d{2}$/.test(month))return;monthlyReports[month]=$('#monthlyReport').value.trim();save();$('#briefState').textContent='Đã lưu';$('#briefState').classList.remove('editing');toast('Đã lưu nhận định tháng')};
$('#closeSummary').onclick=()=>$('#summaryDialog').close();
$('#summaryToCustomers').onclick=()=>{$('#summaryDialog').close();switchView('customers')};
$('#status').innerHTML=STAGES.map(s=>`<option value="${s.id}">${s.label}</option>`).join('');refreshMonthFilter();$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));$('#addCustomerBtn').onclick=()=>openDialog();$('#closeDialog').onclick=$('#cancelDialog').onclick=()=>$('#customerDialog').close();$('#deleteCustomerBtn').onclick=()=>{const id=+$('#customerId').value,current=customers.find(x=>x.id===id);if(!current)return;if(!confirm(`Xoá khách hàng “${current.company}”?\nHành động này không thể hoàn tác.`))return;customers=customers.filter(x=>x.id!==id);save();refreshMonthFilter();$('#customerDialog').close();renderAll();toast('Đã xoá khách hàng')};$('#customerForm').onsubmit=e=>{e.preventDefault();const id=+$('#customerId').value;const data={id:id||Date.now()};['company','contact','phone','email','taxId','website','source','created','status','qualification','owner','followup','apiInterest','product','contractLink','appendixLink','note'].forEach(k=>data[k]=$('#'+k).value);if(id)customers=customers.map(x=>x.id===id?data:x);else customers.unshift(data);save();refreshMonthFilter(data.created.slice(0,7));$('#customerDialog').close();renderAll();toast(id?'Đã cập nhật khách hàng':'Đã thêm khách hàng mới')};$('#searchInput').oninput=renderAll;$('#monthFilter').onchange=()=>{localStorage.setItem('cas-crm-report-month',$('#monthFilter').value);renderAll()};renderAll();loadFromSheets();
const sidebarToggle=$('#sidebarToggle');if(sidebarToggle){const applySidebarState=collapsed=>{document.body.classList.toggle('sidebar-collapsed',collapsed);sidebarToggle.classList.toggle('collapsed',collapsed);sidebarToggle.title=collapsed?'Mở rộng menu':'Thu gọn menu'};applySidebarState(localStorage.getItem('cas-crm-sidebar-collapsed')==='1');sidebarToggle.onclick=()=>{const collapsed=!document.body.classList.contains('sidebar-collapsed');localStorage.setItem('cas-crm-sidebar-collapsed',collapsed?'1':'0');applySidebarState(collapsed)}}
